# lambda has no name. It is a anonymous function

# syntax lambda parameter : function body (also known as expression)

a=(lambda x,y : x+y) (2,3) #passing value to lambda function

b = lambda x,y,z : x*y*z

print(b(1,2,3))



# The map function map(function, sequence) The map() function in python takes in function in python takes in a function list as argument. And function is applied on each element of sequence



sumoftwolist=list(map(lambda x,y: x+y ,[1,2,3,4],[5,6,7,8])) #output generated by shortest list is there is different length of list exist.
print(sumoftwolist)





